### ISSUE TITLE
The only traceroute go library that worked flawlessly.

### ISSUE THREAD

**Issue by unikzforce** [Kseleven/traceroute-go#1]
This is not a real issue, 

I just want to say thanks for this lib,
this is actually the best correctly working golang traceroute library,
i got disappointed by other libs.
i don't know why this lib doesn't have more stars.

feel free to close the issue

**Comment by Kseleven** [comment]
> This is not a real issue,
> 
> I just want to say thanks for this lib, this is actually the best correctly working golang traceroute library, i got disappointed by other libs. i don't know why this lib doesn't have more stars.
> 
> feel free to close the issue

Thanks
